In [6]:
import torch
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
torch.manual_seed(1)

In [35]:
def NLLLoss(logs, targets):
    out = torch.zeros_like(targets, dtype=torch.float)
    for i in range(len(targets)):
        out[i] = logs[i][targets[i]]
    return -out.sum()/len(out)

In [3]:
x = torch.randn(3, 5)
y = torch.LongTensor([0, 1, 2])

In [8]:
x;x.shape
y

tensor([[ 0.2673, -0.4212, -0.5107, -1.5727, -0.1232],
        [ 3.5870, -1.8313,  1.5987, -1.2770,  0.3255],
        [-0.4791,  1.3790,  2.5286,  0.4107, -0.9880]])

torch.Size([3, 5])

tensor([0, 1, 2])

In [50]:
import torch.nn.functional as F

In [54]:
F.nll_loss(x, y)

tensor(-0.3215)

In [58]:
# NLLLoss negative log likelikehood loss. it is just the mean of the log softmax
x_sm = torch.softmax(x, 1) # softmax on rows axis=1
x_log = torch.log(x_sm)
(-(x_log[0,0])-(x_log[1,1])-(x_log[2,2]))/3

tensor(2.3449)

In [48]:
nll_loss = torch.nn.NLLLoss()
print("Torch NLL loss: ", nll_loss(x, y))

Torch NLL loss:  tensor(-0.3215)


In [43]:
x_sm = torch.softmax(x, 1) # softmax on rows axis=1
x_sm


tensor([[0.3575, 0.1796, 0.1642, 0.0568, 0.2419],
        [0.8422, 0.0037, 0.1153, 0.0065, 0.0323],
        [0.0326, 0.2089, 0.6596, 0.0793, 0.0196]])

In [44]:

log_softmax = torch.nn.LogSoftmax(dim=1)
x_log = log_softmax(x)
x_log

tensor([[-1.0286, -1.7171, -1.8066, -2.8686, -1.4192],
        [-0.1718, -5.5901, -2.1601, -5.0358, -3.4333],
        [-3.4239, -1.5657, -0.4162, -2.5340, -3.9328]])

tensor([[-1.0286, -1.7171, -1.8066, -2.8686, -1.4192],
        [-0.1718, -5.5901, -2.1601, -5.0358, -3.4333],
        [-3.4239, -1.5657, -0.4162, -2.5340, -3.9328]])

In [16]:
torch.nn.CrossEntropyLoss??
# This criterion combines :func:`nn.LogSoftmax` and :func:`nn.NLLLoss` in one single class.

In [41]:
cross_entropy_loss = torch.nn.CrossEntropyLoss()
print("Torch CrossEntropyLoss: ", cross_entropy_loss(x, y))

Torch CrossEntropyLoss:  tensor(2.3449)


In [42]:
# crossentropyloss is just the mean of negative log probabilities of correct class. you can look up.
(-torch.log(x_sm[0,0])-torch.log(x_sm[1,1])-torch.log(x_sm[2,2]))/3

tensor(2.3449)

In [34]:
nll_loss = torch.nn.NLLLoss()
print("Torch NLL loss: ", nll_loss(x_log, y))

Torch NLL loss:  tensor(2.3449)


In [36]:
print("Custom NLL loss: ", NLLLoss(x_log, y))

Custom NLL loss:  tensor(2.3449)
